/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

/**
 *
 * @author YAHYA
 */
public class viewDataTeller extends javax.swing.JFrame {

    /**
     * Creates new form viewDataTeller
     */
    public viewDataTeller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idPetugas = new javax.swing.JTextField();
        namaPetugas = new javax.swing.JTextField();
        AlamatPetugas = new javax.swing.JTextField();
        tglLahirPetugas = new javax.swing.JTextField();
        lamaPetugas = new javax.swing.JTextField();
        jenisService = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(idPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 310, 40));

        namaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(namaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 310, 40));

        AlamatPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(AlamatPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 310, 40));

        tglLahirPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglLahirPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(tglLahirPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 310, 40));

        lamaPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamaPetugasActionPerformed(evt);
            }
        });
        getContentPane().add(lamaPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 310, 40));

        jenisService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisServiceActionPerformed(evt);
            }
        });
        getContentPane().add(jenisService, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 310, 40));

        batal.setText("Batal");
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, 80, 40));

        ok.setText("OK");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\TUBES\\tubespbo\\TUBES\\background\\18.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1046, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lamaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamaPetugasActionPerformed

    private void idPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPetugasActionPerformed

    private void namaPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPetugasActionPerformed

    private void AlamatPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatPetugasActionPerformed

    private void jenisServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisServiceActionPerformed

    private void tglLahirPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglLahirPetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglLahirPetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDataTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDataTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDataTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDataTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDataTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatPetugas;
    private javax.swing.JButton batal;
    private javax.swing.JTextField idPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jenisService;
    private javax.swing.JTextField lamaPetugas;
    private javax.swing.JTextField namaPetugas;
    private javax.swing.JButton ok;
    private javax.swing.JTextField tglLahirPetugas;
    // End of variables declaration//GEN-END:variables
}
