/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

/**
 *
 * @author YAHYA
 */
public class viewDataPetugasCS extends javax.swing.JFrame {

    /**
     * Creates new form viewDataPetugasCS
     */
    public viewDataPetugasCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisServicePetugasCS = new javax.swing.JTextField();
        idPetugasCS = new javax.swing.JTextField();
        namaPetugasCS = new javax.swing.JTextField();
        alamatPetugasCS = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        tanggalLahirPetugasCS = new javax.swing.JTextField();
        lamaBekerjaPetugasCS = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jenisServicePetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 300, 40));
        getContentPane().add(idPetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 300, 40));
        getContentPane().add(namaPetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 300, 40));
        getContentPane().add(alamatPetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 300, 40));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 300, 40));
        getContentPane().add(tanggalLahirPetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 300, 40));
        getContentPane().add(lamaBekerjaPetugasCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 300, 40));

        batal.setText("Batal");
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, 70, 40));

        ok.setText("OK");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 660, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\GitHub\\TUBES\\tubespbo\\TUBES\\background\\19.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1047, 743));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDataPetugasCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDataPetugasCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDataPetugasCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDataPetugasCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewDataPetugasCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPetugasCS;
    private javax.swing.JButton batal;
    private javax.swing.JTextField idPetugasCS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jenisServicePetugasCS;
    private javax.swing.JTextField lamaBekerjaPetugasCS;
    private javax.swing.JTextField namaPetugasCS;
    private javax.swing.JButton ok;
    private javax.swing.JTextField tanggalLahirPetugasCS;
    // End of variables declaration//GEN-END:variables
}
